runtime: python312

instance_class: F1

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 0
  max_instances: 5

env_variables:
  PORT: "8080"

entrypoint: gunicorn -b :$PORT "app:create_app()"

handlers:
- url: /static
  static_dir: frontend/static
  secure: always

- url: /.*
  script: auto
  secure: always 