runtime: python311

# App Engine Standard Environment

instance_class: F2

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10

env_variables:
  FLASK_ENV: "production"
  GAE_ENV: "standard"

handlers:
# Serve the React app for the root
- url: /
  static_files: dist/index.html
  upload: dist/index.html

# Serve static assets from the React build
- url: /assets
  static_dir: dist/assets

# Serve any other static files from the React build
- url: /(.*\.(js|css|map|ico|png|jpg|jpeg|svg|json))$
  static_files: dist/\1
  upload: dist/.*\.(js|css|map|ico|png|jpg|jpeg|svg|json)$

# Route API calls to the Flask app
- url: /api/.*
  script: auto

# Health check endpoint
- url: /health
  script: auto

# Catch all handler for React Router
- url: /.*
  static_files: dist/index.html
  upload: dist/index.html 