runtime: python311
entrypoint: gunicorn -b :$PORT main:app

instance_class: F1

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 0
  max_instances: 10

env_variables:
  FLASK_ENV: "production"
  GAE_ENV: "standard"

handlers:
# Serve the favicon
- url: /favicon\.ico
  static_files: dist/image.png
  upload: dist/image.png

# Serve the React app index for root
- url: /$
  static_files: dist/index.html
  upload: dist/index.html

# Serve static assets from the React build
- url: /assets
  static_dir: dist/assets

# Serve the image file
- url: /image\.png
  static_files: dist/image.png
  upload: dist/image.png

# Route API calls to the Flask app
- url: /api/.*
  script: auto

# Health check endpoint
- url: /health
  script: auto

# Catch all other routes - serve React app (for client-side routing)
- url: /.*
  static_files: dist/index.html
  upload: dist/index.html 